/**
 * Author: Joris Rietveld <jorisrietveld@gmail.com>
 * Created: 19-10-2017 16:28
 * License: GPLv3 - General Public License version 3
 */

#define IMPERIAL_SYSTEM
#define METRIC_SYSTEM

volatile uint8_t screenWriteBuffer[4][8] = { // The buffer that stores the currently displayed values.
        {0...8 = 255}, // Initiate the buffer for display 0 with 0Xff so all displays are off.
        {0...8 = 255}, // Initiate the buffer for display 1 with 0Xff so all displays are off.
        {0...8 = 255}, // Initiate the buffer for display 2 with 0Xff so all displays are off.
        {0...8 = 255}, // Initiate the buffer for display 3 with 0Xff so all displays are off.
};

volatile uint64_t odoMeterPulseCount = 0; // The amount of pulses generated by the odometer.
volatile uint64_t rmsMeterStartValue = 0; // The amount of pulses fetched from the odometerPulseCounter when the sample started.
volatile uint64_t dayMeterStartValue = 0; // The amount of pulses fetched from the odometerPulseCounter when the sample started.
volatile uint64_t drivingSpeedStartValue = 0; // The amount of pulses fetched from the odometerPulseCounter when the sample started.

volatile uint32_t currentOdoMeterDistance = 0; // The current distance the car has traveled since its fabrication. (in kilometers/miles depending on the localization settings)
volatile uint16_t currentResolutionsPerMinute = 0; // The current amount resolutions of the car engine.
volatile uint32_t currentDayMeterDistance = 0; // The current distance the car has traveled since the last day meter reset. ( in kilometers/miles per hour depending on the localization settings)
volatile uint16_t currentDrivingSpeed = 0; // The current driving speed of the car. ( in kilometers/miles per hour depending on the localization settings)

// todo routine to update display
/**
 * The display multiplex routine
 * fetch the next byte of the encoded segment buffer
 * write the next byte to the segment ports
 * increment the segment index array.
 */

// Todo routine to update pulse counter
/**
 * The external interrupt routine.
 * increment the pulse counter.
 */

// Todo routing to sample measurement
/**
 * The sampler routine is responsible for updating the the display preparation buffer.
 * calculate the current driving speed
 * calculate the current Odometer value
 * calculate the current Day meter value
 * calculate the current Tachometer value
 */


// Todo initiating the I/O ports on the device

// Todo writing the main routine of the device

void initRegisters();
void updateWriteBuffer();

void main()
{
    intitRegistetrs();
}

void initRegisters()
{
    // todo init IO directions
    // Todo init timers

    // TCNT0 - Timer/Counter 0
    TCNT0 = 0; // Initiate the timer/counter register of timer 0  with an value of 0;

    /** TCCR0 - Timer/Counter Control register 0,  option bits: FOC 0 | WGM 00 | COM 01 | COM 00 | WGM 01 | CS 02 | CS 01 | CS 00 |
     * CS - Clock select settings:
     * Modue 0  = 0b00000000    = 0x00     =  (0 << CS02) | (0 << CS01) | (0 << CS01)   =   Timer off
     * Modue 1  = 0b00000001    = 0x01     =  (0 << CS02) | (0 << CS01) | (1 << CS01)   =   Internal Clock / 0     =  Prescaler disapled
     * Modue 2  = 0b00000010    = 0x02     =  (0 << CS02) | (1 << CS01) | (0 << CS01)   =   Internal Clock / 8     =  From Prescaler
     * Modue 3  = 0b00000011    = 0x03     =  (0 << CS02) | (1 << CS01) | (1 << CS01)   =   Internal Clock / 64    =  From Prescaler
     * Modue 4  = 0b00000100    = 0x04     =  (1 << CS02) | (0 << CS01) | (0 << CS01)   =   Internal Clock / 256   =  From Prescaler
     * Modue 5  = 0b00000101    = 0x05     =  (1 << CS02) | (0 << CS01) | (1 << CS01)   =   Internal Clock / 1024  =  From Prescaler
     * Modue 5  = 0b00000110    = 0x06     =  (1 << CS02) | (1 << CS01) | (0 << CS01)   =   External clock on pin
     */


    // Todo init interrupts
}

void updateWriteBuffer()
{

}
